### PR TITLE
Issue #1108 - Challenges Advertising Bug Fix 1

### PR DESCRIPTION
**Pull request by dexyk**
Issue #1108
Fixed bug loading challenges advertising. Other issue is in technology array in data received which contained duplicates ('iOS 8.0' twice) so tracking by $index was put in user.challenges.advertising.html.

### CODE REVIEW

**Comment by skyhit** [comment]
what is this fix belong to?

**Comment by dexyk** [comment]
Support for challenges advertising widget.

**Comment by skyhit** [comment]
OK, thanks

**Comment by skyhit** [comment]
for DF2F case, the icon background is not enough, can you help fix that?

**Comment by dexyk** [comment]
Check it https://github.com/cloudspokes/arena-web/pull/1109/files

**Pull request closed without merging**
