### PR TITLE
Head Nav Update and Profile Overview

### PR DESCRIPTION
**Pull request by amethystlei**
the tc time directive template is at app/partials/user.tctime.html
Now it is using the prototype code and I put the assembly code in comments because the assembly code is using client's time.

### CODE REVIEW

**Comment by skyhit** [comment]
1. for TC Time, we already have the time, please check https://github.com/cloudspokes/arena-web/blob/master/app/js/resolvers.js#L127-L129

and https://github.com/cloudspokes/arena-web/blob/master/app/partials/user.dashboard.html#L12

update your widget to use that time.
2. for connection status, it is switching from connected and disconnected status, auto-matically, it is for showing the functionality, but can we set the to connected?

**Comment by amethystlei** [comment]
1. Changed back, but it shows my local time, not TC time. Is that expected?

**Comment by skyhit** [comment]
IN app/partials/user.tctime.html, why there are two TC Time?

**Comment by amethystlei** [comment]
Updated. Now demo for connection status is disabled. Do I have to remove the demo code too?

**Pull request merged**
